=== imjagpul/ultraglot/xml/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://srubarovi.cz/teacher" targetNamespace="http://srubarovi.cz/teacher" xmlns="http://srubarovi.cz/teacher" elementFormDefault="qualified">
  <!-- 
      XML Schema Primer: http://www.w3.org/TR/xmlschema-0/
      Structures recommendation: http://www.w3.org/TR/xmlschema-1/
      Datatypes recommendation: http://www.w3.org/TR/xmlschema-2/
  -->
  <!--
  TODO:
  accents
  make unique names restriction
  restrict language codes
  -->
  <xsd:include schemaLocation="shared.xsd" />
  <xsd:element name="language">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="wordTypes" type="ns:wordTypes" minOccurs="0" maxOccurs="1" />
        <xsd:element name="accentDefinition" type="ns:accentDefiniton" minOccurs="0" maxOccurs="1" />
      </xsd:all>
      <xsd:attribute name="name" type="xsd:string" use="required" />
      <xsd:attribute name="langcode" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="wordType">
    <xsd:sequence>
      <xsd:element name="subName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="wordType" type="ns:wordType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="fastAccess" type="ns:fastAccess" />
    <xsd:attribute name="name" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="wordTypes">
    <xsd:sequence>
      <xsd:element name="subName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="wordType" type="ns:wordType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="accentDefiniton">
    <xsd:sequence>
    </xsd:sequence>
    <xsd:attribute name="legalCharacters" type="xsd:string" use="optional" />
    <xsd:attribute name="showAs" type="xsd:string" use="optional" />
  </xsd:complexType>
</xsd:schema>

=== imjagpul/ultraglot/slovniky/ru/.langdef.xml
<?xml version="1.0" encoding="UTF-8"?>

<language xmlns='http://srubarovi.cz/teacher'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://srubarovi.cz/teacher file:/C:/JavaProjekty/Teacher/xml/language.xsd'
  name="Russian (русский)"
  langcode="ru">

  <accentDefinition legalCharacters="аеёиыоуяюАЕЁИЫОУЯЮ" />
  
  <wordTypes>
    <subName>Часть речи</subName>
    <!--
    Русские части речи:
      1. Самостоятельные части речи
        * существительное
        * прилагательное
        * числительное
        * местоимение
        * глагол
        * наречие
      2. Служебные части речи
        * предлог
        * союз
        * частица
      3. Междометие
        * междометие
    -->    
    <wordType name="существительное" fastAccess="1">
      <subName>Род</subName>
      <!--
      В русском языке выделяют следующие виды грамматического рода:
        * мужской
        * женский
        * средний
        * общий (двоякая модель согласования: бедный сирота/бедная сирота)
        * обоюдный (одна модель согласования: он/она настоящая собака)
      -->
      <wordType name="мужской" fastAccess="1"></wordType>
      <wordType name="женский" fastAccess="2"></wordType>
      <wordType name="средний" fastAccess="3"></wordType>
      
      <wordType name="общий" fastAccess="4"></wordType>
      <wordType name="обоюдный" fastAccess="5"></wordType>
    </wordType>
    <wordType name="прилагательное" fastAccess="2"></wordType>
    <wordType name="местоимение" fastAccess="3"></wordType>
    <wordType name="числительное" fastAccess="4"></wordType>
    <wordType name="глагол" fastAccess="5"></wordType>
    <wordType name="наречие" fastAccess="6"></wordType>
    <wordType name="предлог" fastAccess="7"></wordType>
    <wordType name="союз" fastAccess="8"></wordType>
    <wordType name="частица" fastAccess="9"></wordType>
    <wordType name="междометие" fastAccess="0"></wordType>
  </wordTypes>
</language>
